[package]
name = "AnomalyLauncher"
version = "1.0.0"
edition = "2024"

[dependencies]
eframe = { version = "0.36.2", features = ["glow"], default-features = false }
rfd = { version = "0.17.2", default-features = false }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
image = "0.25.10"
thiserror = "2.0.21"
anyhow = "1.0.104"

[profile.dev]
opt-level = 1
debug = "line-tables-only"

[profile.dev.package."*"]
opt-level = 2
debug = false

[profile.release]
panic = "abort"
opt-level = 3
lto = "fat"
strip = true

[build-dependencies]
winresource = "0.1.31"
